### ISSUE TITLE
help with configuration.

### ISSUE THREAD

**Issue by jilabaca** [Jericho1060/du-storage-monitoring#8] opened 2022-10-12 18:12 UTC
Hello, First of all, thank you very much for the script, it looks very good!, but I also didn't understand much how to make it work, first of all I don't speak English natively, so I am using the google translator to help me.

I wanted to know what the name of the containers is like, I currently have several containers, some with a single product and others with several, how is the itemid?

Excuse me if I didn't explain myself well.

**Comment by thoda-dev** [comment] 2022-10-12 18:54
Hi, that script can only monitor one single item by container.

If you want to check for several items, have a look in https://github.com/Jericho1060/du-container-monitoring but that's only for one container (there is a query limit in the container api for DU)

That script is not using the api, that's why it can't detect several items in one container, but no limit for that system.

About the container name, i'll take the example of Pure Carbon, the ID is 159858782, if you want to display it on the 1st screen, name the container `s1_159858782` if it's a container hub you must specify the size and the number of containers, eg: `s1_159858782_L_2` for two L containers connected to the hub

**Comment by thoda-dev** [comment] 2022-10-14 10:22
hope you solved your problem, i'm closing the issue as it's not a bug, you can join my guilded server for more help if needed : https://guilded.jericho.dev

**Closed as completed by thoda-dev** 2022-10-14 10:22 UTC
